### ISSUE TITLE
Exception: failed to pack apk

### ISSUE THREAD

**Issue by robo187** [LuigiVampa92/xapk-to-apk#2]
**Windows 10 using WSL2. Debian.**
Successfully installed & tested these tools python3, apktool, zipalign and apksigner.
Successfully generated a **_xapktoapk.sign.properties_** file with default Android SDK debug keystore.
Test apk is [AI_Bubble_GPT_chat_in_any_app.xapk](https://apkcombo.com/ai-bubble-gpt-chat-in-any-app/the.bravenewworld.input/download/apk) [Package ID: _the.bravenewworld.input_]
```
┌──(username㉿DESKTOP)-[~/xapk-to-apk]
└─$ python3 xapktoapk.py test.xapk
[*] start
[*] unpacking xapk
[*] xapk file unpacked. 3 parts discovered
[*] unpacking 1 of 3
[*] unpacking 2 of 3
[*] unpacking 3 of 3
[*] repack apk
Traceback (most recent call last):
  File "/home/username/xapk-to-apk/xapktoapk.py", line 588, in <module>
    main()
  File "/home/username/xapk-to-apk/xapktoapk.py", line 579, in main
    build_single_apk(path_dir_tmp, apk_main['apk_dir_path'], should_sign_apk, sign_properties)
  File "/home/username/xapk-to-apk/xapktoapk.py", line 439, in build_single_apk
    pack_apk(path_to_tmp_dir, path_to_main_apk_dir)
  File "/home/username/xapk-to-apk/xapktoapk.py", line 318, in pack_apk
    raise Exception("failed to pack apk")
Exception: failed to pack apk

┌──(username㉿DESKTOP)-[~/xapk-to-apk]
└─$
```

Investiaging manually...

```┌──(username㉿DESKTOP)-[~/xapk-to-apk]
└─$ apktool b ./.xapktoapk/the.bravenewworld.input
I: Using Apktool 2.7.0-dirty
I: Checking whether resources has changed...
I: Building resources...
W: aapt: brut.common.BrutException: brut.common.BrutException: Could not extract resource: /prebuilt/linux/aapt_64 (defaulting to $PATH binary)
W: res/drawable/$avd_hide_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_hide_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__0.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__1.xml: Invalid file name: must contain only [a-z0-9_.]
W: res/drawable/$avd_show_password__2.xml: Invalid file name: must contain only [a-z0-9_.]
brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [aapt, p, --min-sdk-version, 23, --target-sdk-version, 33, --version-code, 112401470, --version-name, 0.0.2, --no-version-vectors, -F, /tmp/APKTOOL6790195097454407399.tmp, -0, META-INF/androidx.activity_activity.version, -0, META-INF/androidx.annotation_annotation-experimental.version, -0, META-INF/androidx.appcompat_appcompat-resources.version, -0, META-INF/androidx.appcompat_appcompat.version, -0, META-INF/androidx.arch.core_core-runtime.version, -0, META-INF/androidx.asynclayoutinflater_asynclayoutinflater.version, -0, META-INF/androidx.browser_browser.version, -0, META-INF/androidx.cardview_cardview.version, -0, META-INF/androidx.coordinatorlayout_coordinatorlayout.version, -0, META-INF/androidx.core_core-ktx.version, -0, META-INF/androidx.core_core.version, -0, META-INF/androidx.cursoradapter_cursoradapter.version, -0, META-INF/androidx.customview_customview.version, -0, META-INF/androidx.databinding_baseAdapters.version, -0, META-INF/androidx.databinding_databindingKtx.version, -0, META-INF/androidx.databinding_library.version, -0, META-INF/androidx.databinding_viewbinding.version, -0, META-INF/androidx.documentfile_documentfile.version, -0, META-INF/androidx.drawerlayout_drawerlayout.version, -0, META-INF/androidx.dynamicanimation_dynamicanimation-ktx.version, -0, META-INF/androidx.dynamicanimation_dynamicanimation.version, -0, META-INF/androidx.emoji2_emoji2-views-helper.version, -0, META-INF/androidx.emoji2_emoji2.version, -0, META-INF/androidx.fragment_fragment.version, -0, META-INF/androidx.interpolator_interpolator.version, -0, META-INF/androidx.legacy_legacy-support-core-ui.version, -0, META-INF/androidx.legacy_legacy-support-core-utils.version, -0, META-INF/androidx.legacy_legacy-support-v4.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata-core.version, -0, META-INF/androidx.lifecycle_lifecycle-livedata.version, -0, META-INF/androidx.lifecycle_lifecycle-process.version, -0, META-INF/androidx.lifecycle_lifecycle-runtime-ktx.version, -0, META-INF/androidx.lifecycle_lifecycle-runtime.version, -0, META-INF/androidx.lifecycle_lifecycle-service.version, -0, META-INF/androidx.lifecycle_lifecycle-viewmodel-savedstate.version, -0, META-INF/androidx.lifecycle_lifecycle-viewmodel.version, -0, META-INF/androidx.loader_loader.version, -0, META-INF/androidx.localbroadcastmanager_localbroadcastmanager.version, -0, META-INF/androidx.media_media.version, -0, META-INF/androidx.palette_palette-ktx.version, -0, META-INF/androidx.palette_palette.version, -0, META-INF/androidx.print_print.version, -0, META-INF/androidx.recyclerview_recyclerview.version, -0, META-INF/androidx.savedstate_savedstate.version, -0, META-INF/androidx.slidingpanelayout_slidingpanelayout.version, -0, META-INF/androidx.startup_startup-runtime.version, -0, META-INF/androidx.swiperefreshlayout_swiperefreshlayout.version, -0, META-INF/androidx.tracing_tracing.version, -0, META-INF/androidx.transition_transition.version, -0, META-INF/androidx.vectordrawable_vectordrawable-animated.version, -0, META-INF/androidx.vectordrawable_vectordrawable.version, -0, META-INF/androidx.versionedparcelable_versionedparcelable.version, -0, META-INF/androidx.viewpager2_viewpager2.version, -0, META-INF/androidx.viewpager_viewpager.version, -0, META-INF/com.google.android.material_material.version, -0, META-INF/kotlinx_coroutines_android.version, -0, META-INF/kotlinx_coroutines_core.version, -0, META-INF/kotlinx_coroutines_reactive.version, -0, META-INF/kotlinx_coroutines_rx2.version, -0, META-INF/services/b9.j, -0, META-INF/services/w6.a, -0, META-INF/services/z8.v, -0, assets/8tbwIQXSNUSMQhWn, -0, assets/KbXRbmtJ3f9m519J, -0, assets/Luwdc4TYjP78oRNg, -0, assets/S19L1LahWq6tnmND, -0, assets/XmTgGK507eKb7IBA, -0, assets/ZZjAy1cir9hIGgJA, -0, assets/m0KIuxpr0lwT9fqv, -0, lib/arm64-v8a/libmmkv.so, -0, lib/arm64-v8a/libpairipcore.so, -0, res/mipmap-hdpi/ic_default.webp, -0, res/mipmap-mdpi/ic_default.webp, -0, res/mipmap-xhdpi/ic_default.webp, -0, res/mipmap-xxhdpi/ic_default.webp, -0, res/mipmap-xxxhdpi/ic_default.webp, -0, resources.arsc, -0, webp, -0, res/mipmap-xxxhdpi/ic_default.webp, -0, arsc, -I, /home/username/.local/share/apktool/framework/1.apk, -S, /home/username/xapk-to-apk/./.xapktoapk/the.bravenewworld.input/res, -M, /home/username/xapk-to-apk/./.xapktoapk/the.bravenewworld.input/AndroidManifest.xml]
```

**Comment by a365344743s** [comment]
try apktool --use-aapt2, or use Apktool v2.9.0 and above.

**Comment by shayaknyc** [comment]
I had a similar issue as @robo187 so I installed Apktool v2.9.3 as @a365344743s had suggested. Now, this is the output I receive when executing:
```
user@host:~/git/xapk-to-apk$ ./xapktoapk.py Reddit_2024.32.1_APKPure.xapk
/home/user/git/xapk-to-apk/./xapktoapk.py:9: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.spawn import find_executable
[*] start
[*] unpacking xapk
[*] xapk file unpacked. 20 parts discovered
[*] unpacking 1 of 20
[*] unpacking 2 of 20
[*] unpacking 3 of 20
[*] unpacking 4 of 20
[*] unpacking 5 of 20
[*] unpacking 6 of 20
[*] unpacking 7 of 20
[*] unpacking 8 of 20
[*] unpacking 9 of 20
[*] unpacking 10 of 20
[*] unpacking 11 of 20
[*] unpacking 12 of 20
[*] unpacking 13 of 20
Traceback (most recent call last):
  File "/home/user/git/xapk-to-apk/./xapktoapk.py", line 588, in <module>
    main()
  File "/home/user/git/xapk-to-apk/./xapktoapk.py", line 560, in main
    unpack_apk(path_dir_tmp, apk_file, index + 1, unpack_number_total)
  File "/home/user/git/xapk-to-apk/./xapktoapk.py", line 309, in unpack_apk
    raise Exception("failed to unpack %s" % apk_file)
Exception: failed to unpack com.reddit.frontpage.apk
```

Now, if I manually run the command that's failing, I get this:
```
user@host:~/git/xapk-to-apk$ apktool d -s Reddit_2024.32.1_APKPure.xapk
I: Using Apktool 2.9.3 on Reddit_2024.32.1_APKPure.xapk
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
```
And this is the output:
```
user@host:~/git/xapk-to-apk/Reddit_2024.32.1_APKPure.xapk.out$ ll
Permissions Size User  Date Modified Name
drwxr-xr-x     - user  8 Aug 16:44   original
drwxr-xr-x     - user  8 Aug 16:44   unknown
.rw-r--r--   766 user  8 Aug 16:44   apktool.yml
```

Here's the directory listing for the `unknown` directory:
```
user@host:~/git/xapk-to-apk/Reddit_2024.32.1_APKPure.xapk.out/unknown$ ll
Permissions Size User  Date Modified Name
.rw-r--r--  100M user  8 Aug 16:44   com.reddit.frontpage.apk
.rw-r--r--  1.1M user  8 Aug 16:44   config.ar.apk
.rw-r--r--  349k user  8 Aug 16:44   config.armeabi_v7a.apk
.rw-r--r--  840k user  8 Aug 16:44   config.de.apk
.rw-r--r--  1.2M user  8 Aug 16:44   config.en.apk
.rw-r--r--  1.2M user  8 Aug 16:44   config.es.apk
.rw-r--r--  897k user  8 Aug 16:44   config.fr.apk
.rw-r--r--  2.5M user  8 Aug 16:44   config.hdpi.apk
.rw-r--r--   99k user  8 Aug 16:44   config.hi.apk
.rw-r--r--   91k user  8 Aug 16:44   config.in.apk
.rw-r--r--  824k user  8 Aug 16:44   config.it.apk
.rw-r--r--   95k user  8 Aug 16:44   config.ja.apk
.rw-r--r--   95k user  8 Aug 16:44   config.ko.apk
.rw-r--r--  131k user  8 Aug 16:44   config.my.apk
.rw-r--r--  1.2M user  8 Aug 16:44   config.pt.apk
.rw-r--r--   95k user  8 Aug 16:44   config.ru.apk
.rw-r--r--   95k user  8 Aug 16:44   config.th.apk
.rw-r--r--   91k user  8 Aug 16:44   config.tr.apk
.rw-r--r--   95k user  8 Aug 16:44   config.vi.apk
.rw-r--r--  168k user  8 Aug 16:44   config.zh.apk
.rw-r--r--   51k user  8 Aug 16:44   icon.png
.rw-r--r--  3.5k user  8 Aug 16:44   manifest.json
```
So it seems as if on CLI the command `apktool d -s [FILENAME.APK]` is correctly splitting the xapk file? But the Python script is somehow failing somewhere?

Any ideas?

**Comment by MohmmadQunibi** [comment]
@shayaknyc it was able to unpack all the apks with version 2.9.3 but repacking failed again!!!

**Comment by shayaknyc** [comment]
> @shayaknyc it was able to unpack all the apks with version 2.9.3 but repacking failed again!!!

Yeah, I couldn't get it to repack either..... at this point, I've given up, which makes me sad because I can't "revance" the reddit app unless I get a complete APK file.... very annoying LOL

**Comment by MohmmadQunibi** [comment]
> > @shayaknyc it was able to unpack all the apks with version 2.9.3 but repacking failed again!!!
> 
> Yeah, I couldn't get it to repack either..... at this point, I've given up, which makes me sad because I can't "revance" the reddit app unless I get a complete APK file.... very annoying LOL

me too, i was trying to patch the latest version of X (twitter)

**Comment by LuigiVampa92** [comment]
Hi everyone @robo187 @a365344743s @shayaknyc @MohmmadQunibi. Thank you guys for the interest to the project and your attentiveness. Sorry for the late answer, haven't been looking into GitHub repos for a while.

The script indeed had poor compatibility with Windows, unfortunately, but I have recently accepted and merged a pull request that added that compatibility (https://github.com/LuigiVampa92/xapk-to-apk/pull/4). Unfortunately I have no Windows machine to check it out myself, but everything looks right. On my machine I was able to repack and run AI Bubble GPT chat apk mentioned in the first message, and it should work on Windows as well after the fix. 

Can you please check again if it works? Thank you

**Comment by MohmmadQunibi** [comment]
> int, I've given up, whi

@shayaknyc I found a way if you are intreseted

**Comment by MohmmadQunibi** [comment]
> Hi everyone @robo187 @a365344743s @shayaknyc @MohmmadQunibi. Thank you guys for the interest to the project and your attentiveness. Sorry for the late answer, haven't been looking into GitHub repos for a while.
> 
> The script indeed had poor compatibility with Windows, unfortunately, but I have recently accepted and merged a pull request that added that compatibility (#4). Unfortunately I have no Windows machine to check it out myself, but everything looks right. On my machine I was able to repack and run AI Bubble GPT chat apk mentioned in the first message, and it should work on Windows as well after the fix.
> 
> Can you please check again if it works? Thank you

thank you for such great projects, but i rememeber trying this on wsl, which should work there, but i will definitly try the windows script
