### ISSUE TITLE
Running error: Exception: failed to pack apk

### ISSUE THREAD

**Issue by lm379** [LuigiVampa92/xapk-to-apk#5]
I have installed apksigner, zipalign and apktool through apt. My system version is Ubuntu 20.04. But the running error is as follows
```
root@iZt4n1y2rttuje44k7fngbZ:~/xapk-to-apk# python3 xapktoapk.py test.xapk
[*] start
[*] unpacking xapk
[*] xapk file unpacked. 3 parts discovered
[*] unpacking 1 of 3
[*] unpacking 2 of 3
[*] unpacking 3 of 3
[*] repack apk
Traceback (most recent call last):
  File "xapktoapk.py", line 617, in <module>
    main()
  File "xapktoapk.py", line 607, in main
    build_single_apk(path_dir_tmp, apk_main['apk_dir_path'], should_sign_apk, sign_properties)
  File "xapktoapk.py", line 465, in build_single_apk
    pack_apk(path_to_tmp_dir, path_to_main_apk_dir)
  File "xapktoapk.py", line 332, in pack_apk
    raise Exception("failed to pack apk")
Exception: failed to pack apk
```
This xapk file was downloaded from apkpure.
https://apkpure.com/photovoltaic-calculations/it.ettoregallina.calcolifotovoltaici/download

**Comment by chakaponden** [comment]
I have the same issue with every apkx

**Comment by ppeixoto** [comment]
![image](https://github.com/user-attachments/assets/b59bddfe-6cfa-4099-83f1-af9a5860b408)

same issue

**Comment by EDLLT** [comment]
Same here

**Comment by Sicks3c** [comment]
Same here

**Comment by joshuachenn** [comment]
Same here, someone PLEASE HELP~

**Comment by joshuachenn** [comment]
➜  .xapktoapk git:(development) ✗ apktool b com.xxx.xxx
I: Using Apktool 2.9.3
I: Checking whether resources has changed...
I: Building resources...
W: /Users/joshua/SwordRain/Tools/xapk-to-apk/.xapktoapk/com.xxx.xxx/AndroidManifest.xml:1: error: attribute android:requiredSplitTypes not found.
W: /Users/joshua/SwordRain/Tools/xapk-to-apk/.xapktoapk/com.xxx.xxx/AndroidManifest.xml:1: error: attribute android:splitTypes not found.
W: error: failed processing manifest.
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/var/folders/rx/4tv74kl96lsb6xqqh5lvr3gc0000gn/T/brut_util_Jar_26389957360234537271670465818362496186.tmp, link, -o, /var/folders/rx/4tv74kl96lsb6xqqh5lvr3gc0000gn/T/APKTOOL1732084605468849020.tmp, --package-id, 127, --min-sdk-version, 24, --target-sdk-version, 34, --version-code, 802, --version-name, 1.7.27, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --no-compile-sdk-metadata, --warn-manifest-validation, -e, /var/folders/rx/4tv74kl96lsb6xqqh5lvr3gc0000gn/T/APKTOOL8750386181435246866.tmp, -0, arsc, -I, /joshua/Library/apktool/framework/1.apk, --manifest, /joshua/SwordRain/Tools/xapk-to-apk/.xapktoapk/com.gamania.lineagem/AndroidManifest.xml, /joshua/SwordRain/Tools/xapk-to-apk/.xapktoapk/com.gamania.lineagem/build/resources.zip]

**Comment by jcifox** [comment]
Same here, somebody PLEASE~

**Comment by Niek** [comment]
What fixed it for me, was adding `--use-aapt1` to the apktool command (added `--debug` too at the same time):
```diff
diff --git a/xapktoapk.py b/xapktoapk.py
index dfe1452..aecb863 100755
--- a/xapktoapk.py
+++ b/xapktoapk.py
@@ -332,7 +362,7 @@ def pack_apk(path_dir_tmp, main_apk_dir):
     os.chdir(path_dir_tmp)
     apktool = get_executable_in_path('apktool')
     if not apktool is None:
-        rc = execute_command_subprocess([apktool, 'b', main_apk_dir])
+        rc = execute_command_subprocess([apktool, 'b', main_apk_dir, '--use-aapt1', '--debug'])
         if rc != 0:
             raise Exception("failed to pack apk")
     else:
```

**Comment by widow-of-hope** [comment]
I've applied this fix and am still getting the same error output as OP.
